global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'my_nginx_service'
    scheme: http
    static_configs:
      - targets: ["host.docker.internal:8081"]
      
