version: '3'

networks:
  custom_network:
    driver: bridge

services:
  myapp:
    image: musakucuk99/monitoring:latest
    container_name: my_app
    ports:
      - "8081:8080"
      - "8082:443"
    depends_on:
      - app_db
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    networks:
      - custom_network

  load_test:
    image: ubuntu:latest 
    container_name: load_test
    depends_on:
      - app_db
    volumes:
      - ./log_of_loadtest:/var/log
      - ./init:/var/init
    command: ["sh","/var/init/install_and_run.sh"]
    networks:
      - custom_network

  sonar_db:
    image: postgres:13
    hostname: sonar_db
    container_name: sonar_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - custom_network

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - custom_network

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - custom_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - custom_network

  app_db:
    image: postgres:13
    container_name: app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: mydatabase
    volumes:
      - app_db:/var/lib/postgresql
      - app_db_data:/var/lib/postgresql/data
    networks:
      - custom_network

volumes:
  prometheus:
  grafana:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_db:
  sonar_db_data:
  app_db:
  app_db_data:

